name: Go build By Action

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Go version
              uses: actions/setup-go@v5
              with:
                go-version: '1.18'
            - name: Get Date
              id: get-date
              run: |
                echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
              shell: bash
            
            - uses: actions/cache@v4
              env:
                cache-name: go-cache
              with:
                path: |
                    ~/.cache/go-build
                    ~/go/pkg/mod
                # key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
                key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ steps.get-date.outputs.date }}
                restore-keys: |
                    ${{ runner.os }}-build-${{ env.cache-name }}-
                    ${{ runner.os }}-build-
                    ${{ runner.os }}-
            
            - run: go env -w GO111MODULE=auto
            - run: go run -mod=mod hello-world.go
